"""empty message

Revision ID: 100533124c15
Revises: 6168bc1e4c30
Create Date: 2021-07-22 01:08:10.743437

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '100533124c15'
down_revision = '6168bc1e4c30'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('decks', sa.Column('cards', sa.NullType(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('decks', 'cards')
    # ### end Alembic commands ###
