"""empty message

Revision ID: d539d9bf7834
Revises: 6168bc1e4c30
Create Date: 2021-07-25 09:16:30.550142

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd539d9bf7834'
down_revision = '6168bc1e4c30'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('decks', sa.Column('studying', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('decks', 'studying')
    # ### end Alembic commands ###
